package com.matibi.potionsnrituals.config;

import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.awt.Color;

public class ModConfigScreen implements ModMenuApi {

    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return ModConfigScreen::create;
    }

    public static Screen create(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
                .title(Component.translatable("title.potions-n-rituals.config"))

                // ═══════════════════════════════════════════════════════════
                // TAB 1 — Potions & Items
                // ═══════════════════════════════════════════════════════════
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("category.potions-n-rituals.potions_and_items"))

                        // ─── Syringe ──────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("item.potions-n-rituals.syringe"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.syringe.damage"))
                                        .binding(1.0f, () -> ModConfig.get().syringe_damage, v -> ModConfig.get().syringe_damage = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.syringe.durability_loss"))
                                        .binding(1, () -> ModConfig.get().syringe_durability_loss, v -> ModConfig.get().syringe_durability_loss = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.syringe.max_transfer_duration"))
                                        .binding(200, () -> ModConfig.get().syringe_max_transfer_duration_ticks, v -> ModConfig.get().syringe_max_transfer_duration_ticks = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.syringe.durability"))
                                        .binding(20, () -> ModConfig.get().syringe_durability, v -> ModConfig.get().syringe_durability = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Lingering Potion Cooldown ────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.lingering_potion_cooldown"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.lingering_potion_cooldown.cooldown"))
                                        .binding(60, () -> ModConfig.get().lingering_potion_cooldown, v -> ModConfig.get().lingering_potion_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.lingering_potion_cooldown.short_cooldown"))
                                        .binding(20, () -> ModConfig.get().lingering_potion_short_cooldown, v -> ModConfig.get().lingering_potion_short_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.lingering_potion_cooldown.long_cooldown"))
                                        .binding(200, () -> ModConfig.get().lingering_potion_long_cooldown, v -> ModConfig.get().lingering_potion_long_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Splash Potion Cooldown ───────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.splash_potion_cooldown"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.splash_potion_cooldown.cooldown"))
                                        .binding(60, () -> ModConfig.get().splash_potion_cooldown, v -> ModConfig.get().splash_potion_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.splash_potion_cooldown.short_cooldown"))
                                        .binding(20, () -> ModConfig.get().splash_potion_short_cooldown, v -> ModConfig.get().splash_potion_short_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.splash_potion_cooldown.long_cooldown"))
                                        .binding(200, () -> ModConfig.get().splash_potion_long_cooldown, v -> ModConfig.get().splash_potion_long_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Brewing Stand Alternative Fuel ───────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.brewing_stand_alternative_fuel"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.brewing_stand_alternative_fuel.fuel"))
                                        .binding(4, () -> ModConfig.get().blaze_replacer_fuel, v -> ModConfig.get().blaze_replacer_fuel = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Potion Stacks ────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.potion_stacks"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_stacks.max_stack_size"))
                                        .binding(16, () -> ModConfig.get().max_potion_stack, v -> ModConfig.get().max_potion_stack = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Potion duration ──────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.potion_duration"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_duration.instant"))
                                        .binding(1, () -> ModConfig.get().dur_instant, v -> ModConfig.get().dur_instant = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_duration.very_short"))
                                        .binding(200, () -> ModConfig.get().dur_very_short, v -> ModConfig.get().dur_very_short = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_duration.short"))
                                        .binding(900, () -> ModConfig.get().dur_short, v -> ModConfig.get().dur_short = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_duration.basic"))
                                        .binding(3600, () -> ModConfig.get().dur_basic, v -> ModConfig.get().dur_basic = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_duration.long"))
                                        .binding(9600, () -> ModConfig.get().dur_long, v -> ModConfig.get().dur_long = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.potion_duration.infinite"))
                                        .binding(-1, () -> ModConfig.get().dur_inf, v -> ModConfig.get().dur_inf = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Imbued Effect Hit ────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.imbued_effect_hit"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.imbued_effect_hit.default_hit"))
                                        .binding(10, () -> ModConfig.get().default_hit, v -> ModConfig.get().default_hit = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Effect Combination ───────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.effect_combination"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.effect_combination.max_diff"))
                                        .binding(1, () -> ModConfig.get().max_diff, v -> ModConfig.get().max_diff = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Permanent Potion ─────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.permanent_potion"))
                                .collapsed(true)
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.permanent_potion.perm_heal"))
                                        .binding(1.0, () -> ModConfig.get().perm_heal, v -> ModConfig.get().perm_heal = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.permanent_potion.perm_speed"))
                                        .binding(0.01, () -> ModConfig.get().perm_speed, v -> ModConfig.get().perm_speed = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.permanent_potion.perm_strength"))
                                        .binding(0.5, () -> ModConfig.get().perm_strength, v -> ModConfig.get().perm_strength = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .build())

                        .build())

                // ═══════════════════════════════════════════════════════════
                // TAB 2 — Mob Effects
                // ═══════════════════════════════════════════════════════════
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable("category.potions-n-rituals.mob_effects"))

                        // ─── Ghost Walk ───────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.ghost_walk"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ghost_walk.y_movement"))
                                        .binding(0.15f, () -> ModConfig.get().ghost_y_movement, v -> ModConfig.get().ghost_y_movement = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ghost_walk.movement_absorber"))
                                        .binding(0.5f, () -> ModConfig.get().ghost_movement_absorber, v -> ModConfig.get().ghost_movement_absorber = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Ignition ─────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.ignition"))
                                .collapsed(true)
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ignition.fireball_speed"))
                                        .binding(1.5, () -> ModConfig.get().fireball_speed, v -> ModConfig.get().fireball_speed = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ignition.fireball_cooldown"))
                                        .binding(100, () -> ModConfig.get().fireball_cooldown, v -> ModConfig.get().fireball_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Vampirism ────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.vampirism"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.vampirism.heal"))
                                        .binding(0.20f, () -> ModConfig.get().vampirism_heal, v -> ModConfig.get().vampirism_heal = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.vampirism.heal_per_level"))
                                        .binding(0.10f, () -> ModConfig.get().vampirism_heal_per_level, v -> ModConfig.get().vampirism_heal_per_level = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Acid ─────────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.acid"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.acid.radius"))
                                        .binding(1, () -> ModConfig.get().acid_radius, v -> ModConfig.get().acid_radius = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.acid.depth"))
                                        .binding(1, () -> ModConfig.get().acid_depth, v -> ModConfig.get().acid_depth = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.acid.radius_per_level"))
                                        .binding(1, () -> ModConfig.get().acid_radius_per_level, v -> ModConfig.get().acid_radius_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.acid.depth_per_level"))
                                        .binding(1, () -> ModConfig.get().acid_depth_per_level, v -> ModConfig.get().acid_depth_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Frost ────────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.frost"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.frost.radius"))
                                        .binding(1, () -> ModConfig.get().frost_radius, v -> ModConfig.get().frost_radius = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.frost.radius_per_level"))
                                        .binding(1, () -> ModConfig.get().frost_radius_per_level, v -> ModConfig.get().frost_radius_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Giant ────────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.giant"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.giant.max_tries"))
                                        .binding(4, () -> ModConfig.get().growth_max_tries, v -> ModConfig.get().growth_max_tries = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.giant.max_tries_per_level"))
                                        .binding(4, () -> ModConfig.get().growth_max_tries_per_level, v -> ModConfig.get().growth_max_tries_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Resurrection ─────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.resurrection"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resurrection.max_resurrections"))
                                        .binding(5, () -> ModConfig.get().max_resurrection, v -> ModConfig.get().max_resurrection = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Adhesion ─────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.adhesion"))
                                .collapsed(true)
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.adhesion.horizontal_damping"))
                                        .binding(0.90, () -> ModConfig.get().horizontal_damping, v -> ModConfig.get().horizontal_damping = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.adhesion.base_climb"))
                                        .binding(0.20, () -> ModConfig.get().base_climb, v -> ModConfig.get().base_climb = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.adhesion.climb_per_level"))
                                        .binding(0.05, () -> ModConfig.get().climb_per_level, v -> ModConfig.get().climb_per_level = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Aftermath ────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.aftermath"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.aftermath.health_required_after"))
                                        .binding(0.5f, () -> ModConfig.get().health_required_after_aftermath, v -> ModConfig.get().health_required_after_aftermath = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Death ────────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.death"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.death.boss_death_damage"))
                                        .binding(0.5f, () -> ModConfig.get().boss_death_damage, v -> ModConfig.get().boss_death_damage = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.death.undead_death_heal"))
                                        .binding(1.0f, () -> ModConfig.get().undead_death_heal, v -> ModConfig.get().undead_death_heal = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.death.boss_death_backlash"))
                                        .binding(0.5f, () -> ModConfig.get().boss_death_backlash, v -> ModConfig.get().boss_death_backlash = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.death.undead_death_backlash"))
                                        .binding(0.2f, () -> ModConfig.get().undead_death_backlash, v -> ModConfig.get().undead_death_backlash = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Oblivion ─────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.oblivion"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.oblivion.inventory_forgotten_chance"))
                                        .binding(0.25f, () -> ModConfig.get().inventory_forgotten, v -> ModConfig.get().inventory_forgotten = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.oblivion.teleport_max_tries"))
                                        .binding(50, () -> ModConfig.get().tp_max_try, v -> ModConfig.get().tp_max_try = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Ore Sense ────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.ore_sense"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.scan_range"))
                                        .binding(5, () -> ModConfig.get().ore_scan_range, v -> ModConfig.get().ore_scan_range = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.scan_range_per_level"))
                                        .binding(3, () -> ModConfig.get().ore_scan_range_per_level, v -> ModConfig.get().ore_scan_range_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.scan_interval"))
                                        .binding(10, () -> ModConfig.get().ore_scan_interval, v -> ModConfig.get().ore_scan_interval = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.coal_color"))
                                        .binding(new Color(0x2A2A2A), () -> new Color(ModConfig.get().coal_color), v -> ModConfig.get().coal_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.iron_color"))
                                        .binding(new Color(0xD8A98A), () -> new Color(ModConfig.get().iron_color), v -> ModConfig.get().iron_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.gold_color"))
                                        .binding(new Color(0xF0D020), () -> new Color(ModConfig.get().gold_color), v -> ModConfig.get().gold_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.diamond_color"))
                                        .binding(new Color(0x40E0FF), () -> new Color(ModConfig.get().diamond_color), v -> ModConfig.get().diamond_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.emerald_color"))
                                        .binding(new Color(0x00C060), () -> new Color(ModConfig.get().emerald_color), v -> ModConfig.get().emerald_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.lapis_color"))
                                        .binding(new Color(0x1A3FBF), () -> new Color(ModConfig.get().lapis_color), v -> ModConfig.get().lapis_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.redstone_color"))
                                        .binding(new Color(0xFF2010), () -> new Color(ModConfig.get().redstone_color), v -> ModConfig.get().redstone_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.copper_color"))
                                        .binding(new Color(0xE07040), () -> new Color(ModConfig.get().copper_color), v -> ModConfig.get().copper_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.ancient_debris_color"))
                                        .binding(new Color(0x6B3A2A), () -> new Color(ModConfig.get().ancient_debris_color), v -> ModConfig.get().ancient_debris_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.quartz_color"))
                                        .binding(new Color(0xF0EEE8), () -> new Color(ModConfig.get().quartz_color), v -> ModConfig.get().quartz_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Color>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.generic_ore_color"))
                                        .binding(new Color(0xF0C838), () -> new Color(ModConfig.get().ore_color), v -> ModConfig.get().ore_color = v.getRGB())
                                        .controller(ColorControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.alpha_max"))
                                        .binding(0.85f, () -> ModConfig.get().alpha_max, v -> ModConfig.get().alpha_max = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.lerp_speed"))
                                        .binding(0.08f, () -> ModConfig.get().lerp_speed, v -> ModConfig.get().lerp_speed = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.ore_sense.thickness"))
                                        .binding(0.15f, () -> ModConfig.get().thick, v -> ModConfig.get().thick = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Photosynthesis ───────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.photosynthesis"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.photosynthesis.food"))
                                        .binding(1, () -> ModConfig.get().photosynthesis_food, v -> ModConfig.get().photosynthesis_food = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.photosynthesis.base_saturation"))
                                        .binding(0.2f, () -> ModConfig.get().photosynthesis_base_saturation, v -> ModConfig.get().photosynthesis_base_saturation = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.photosynthesis.saturation_per_level"))
                                        .binding(0.1f, () -> ModConfig.get().photosynthesis_saturation_per_level, v -> ModConfig.get().photosynthesis_saturation_per_level = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Resonance ────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.resonance"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.radius"))
                                        .binding(4, () -> ModConfig.get().resonance_radius, v -> ModConfig.get().resonance_radius = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.radius_per_level"))
                                        .binding(2, () -> ModConfig.get().resonance_radius_per_level, v -> ModConfig.get().resonance_radius_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.orbit_points"))
                                        .binding(16, () -> ModConfig.get().orbit_points, v -> ModConfig.get().orbit_points = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.pulse_points"))
                                        .binding(40, () -> ModConfig.get().pulse_points, v -> ModConfig.get().pulse_points = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.scale_orbit"))
                                        .binding(0.45f, () -> ModConfig.get().scale_orbit, v -> ModConfig.get().scale_orbit = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.scale_pulse"))
                                        .binding(0.65f, () -> ModConfig.get().scale_pulse, v -> ModConfig.get().scale_pulse = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.pulse_period"))
                                        .binding(24, () -> ModConfig.get().pulse_period, v -> ModConfig.get().pulse_period = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.resonance.orbit_speed_base"))
                                        .binding(0.08, () -> ModConfig.get().orbit_speed_base, v -> ModConfig.get().orbit_speed_base = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Rust ─────────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.rust"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.rust.damage"))
                                        .binding(0.001f, () -> ModConfig.get().rust_damage, v -> ModConfig.get().rust_damage = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.rust.min_damage"))
                                        .binding(1, () -> ModConfig.get().rust_min_damage, v -> ModConfig.get().rust_min_damage = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Saturation ───────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.saturation"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.saturation.base"))
                                        .binding(0.005f, () -> ModConfig.get().base_saturation, v -> ModConfig.get().base_saturation = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.saturation.per_level"))
                                        .binding(0.005f, () -> ModConfig.get().saturation_per_level, v -> ModConfig.get().saturation_per_level = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Thorns ───────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.thorns"))
                                .collapsed(true)
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.thorns.base"))
                                        .binding(0.2f, () -> ModConfig.get().base_thorns, v -> ModConfig.get().base_thorns = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.thorns.per_level"))
                                        .binding(0.1f, () -> ModConfig.get().thorns_per_level, v -> ModConfig.get().thorns_per_level = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Unstable ─────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.unstable"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.unstable.effect_seconds"))
                                        .binding(8, () -> ModConfig.get().unstable_effect_seconds, v -> ModConfig.get().unstable_effect_seconds = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.unstable.effect_seconds_per_level"))
                                        .binding(8, () -> ModConfig.get().unstable_effect_seconds_per_level, v -> ModConfig.get().unstable_effect_seconds_per_level = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.unstable.explosion_power"))
                                        .binding(2.5f, () -> ModConfig.get().unstable_explosion_power, v -> ModConfig.get().unstable_explosion_power = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.unstable.explosion_power_per_level"))
                                        .binding(1.0f, () -> ModConfig.get().unstable_explosion_power_per_level, v -> ModConfig.get().unstable_explosion_power_per_level = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.unstable.explosion_chance"))
                                        .binding(0.30f, () -> ModConfig.get().unstable_explosion_chance, v -> ModConfig.get().unstable_explosion_chance = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Float>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.unstable.explosion_chance_per_level"))
                                        .binding(0.20f, () -> ModConfig.get().unstable_explosion_chance_per_level, v -> ModConfig.get().unstable_explosion_chance_per_level = v)
                                        .controller(FloatFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Reactivation ─────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.reactivation"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.reactivation.duration"))
                                        .binding(2, () -> ModConfig.get().reactivation_duration, v -> ModConfig.get().reactivation_duration = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Infinity ─────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.infinity"))
                                .collapsed(true)
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.infinity.max_health_lost"))
                                        .binding(4.0, () -> ModConfig.get().max_health_lost_per_effect, v -> ModConfig.get().max_health_lost_per_effect = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Pregnancy ────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.pregnant"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.pregnancy.duration"))
                                        .binding(20 * 60 * 20, () -> ModConfig.get().pregnancy_duration, v -> ModConfig.get().pregnancy_duration = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.pregnancy.max_distance"))
                                        .binding(8.0, () -> ModConfig.get().max_distance_pregnancy, v -> ModConfig.get().max_distance_pregnancy = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Clumsiness ───────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.clumsiness"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.clumsiness.drop_percentage"))
                                        .binding(30, () -> ModConfig.get().drop_percentage, v -> ModConfig.get().drop_percentage = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Cold ─────────────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("effect.potions-n-rituals.cold"))
                                .collapsed(true)
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.cold.min_cough_time"))
                                        .binding(1, () -> ModConfig.get().min_cough_time, v -> ModConfig.get().min_cough_time = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.cold.max_cough_time"))
                                        .binding(10, () -> ModConfig.get().max_cough_time, v -> ModConfig.get().max_cough_time = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        // ─── Active Effect ─────────────────────────────────────────────────
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable("group.potions-n-rituals.active_effect"))
                                .collapsed(true)
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.medusa_range"))
                                        .binding(20.0, () -> ModConfig.get().medusa_range, v -> ModConfig.get().medusa_range = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.medusa_range_per_level"))
                                        .binding(5.0, () -> ModConfig.get().medusa_range_per_level, v -> ModConfig.get().medusa_range_per_level = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.medusa_short_cooldown"))
                                        .binding(100, () -> ModConfig.get().medusa_short_cooldown, v -> ModConfig.get().medusa_short_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.medusa_cooldown"))
                                        .binding(200, () -> ModConfig.get().medusa_cooldown, v -> ModConfig.get().medusa_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.medusa_long_cooldown"))
                                        .binding(600, () -> ModConfig.get().medusa_long_cooldown, v -> ModConfig.get().medusa_long_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.teleport_range"))
                                        .binding(64.0, () -> ModConfig.get().active_teleport_range, v -> ModConfig.get().active_teleport_range = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.teleport_range_per_level"))
                                        .binding(16.0, () -> ModConfig.get().active_teleport_range_per_level, v -> ModConfig.get().active_teleport_range_per_level = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.teleport_short_cooldown"))
                                        .binding(100, () -> ModConfig.get().active_teleport_short_cooldown, v -> ModConfig.get().active_teleport_short_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.teleport_cooldown"))
                                        .binding(200, () -> ModConfig.get().active_teleport_cooldown, v -> ModConfig.get().active_teleport_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.teleport_long_cooldown"))
                                        .binding(600, () -> ModConfig.get().active_teleport_long_cooldown, v -> ModConfig.get().active_teleport_long_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.zeus_range"))
                                        .binding(64.0, () -> ModConfig.get().zeus_range, v -> ModConfig.get().zeus_range = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Double>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.zeus_range_per_level"))
                                        .binding(16.0, () -> ModConfig.get().zeus_range_per_level, v -> ModConfig.get().zeus_range_per_level = v)
                                        .controller(DoubleFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.zeus_short_cooldown"))
                                        .binding(100, () -> ModConfig.get().zeus_short_cooldown, v -> ModConfig.get().zeus_short_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.zeus_cooldown"))
                                        .binding(200, () -> ModConfig.get().zeus_cooldown, v -> ModConfig.get().zeus_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .option(Option.<Integer>createBuilder()
                                        .name(Component.translatable("option.potions-n-rituals.active_effect.zeus_long_cooldown"))
                                        .binding(600, () -> ModConfig.get().zeus_long_cooldown, v -> ModConfig.get().zeus_long_cooldown = v)
                                        .controller(IntegerFieldControllerBuilder::create)
                                        .build())
                                .build())

                        .build())

                .save(ModConfig.HANDLER::save)
                .build()
                .generateScreen(parent);
    }
}
